version: "3.3"

services: 

  dbase:
    image: mariadb
    container_name: dbase
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: serviciospago
      MYSQL_USER: eliudcarmona
      MYSQL_PASSWORD: manzanita69
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./dbdata:/var/lib/mysql
    command: mysqld --default-authentication-plugin=mysql_native_password


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadphp2
    depends_on:
      - dbase
    environment:
      PMA_HOST: dbase
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PMA_USER: root
      PMA_PASSWORD: root
    restart: always
    ports:
      - 80:80




